/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package udc.java

import spock.lang.Specification

class AppTest extends Specification {
    void "test application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
