name: Test

on:
  # Trigger at every push. Action will also be visible from Pull Requests to master
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Java Test
    permissions:
      # contents: read
      # id-token: write
      issues: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java_version: [11, 17, 19]
    runs-on: ${{ matrix.os }}

    steps:
    # Git Checkout
    - name: Checkout Code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Java ${{matrix.java_version}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java_version}}
        distribution: 'temurin'
        architecture: x64
        cache: gradle
       
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Gradle Tests
      run: ./gradlew build test --no-daemon --console=plain --stacktrace --info --warning-mode=all
      working-directory: ./udc-java

    - name: Archive production artifacts
      if: ${{ success() }} || ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: nf-quilt-test-reports
        path: |
          /home/runner/work/nf-quilt/nf-quilt/plugins/nf-quilt/build/reports/tests/test/
